# Generated by Django 5.1.dev20240427013607 on 2024-07-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_hotel', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('etoile', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=20)),
                ('Telephone', models.CharField(max_length=50)),
                ('parking', models.CharField(choices=[('Non', 'Non'), ('Oui', 'Oui')], max_length=20)),
                ('boite', models.CharField(choices=[('Non', 'Non'), ('Oui', 'Oui')], max_length=20)),
                ('bordure', models.CharField(choices=[('Non', 'Non'), ('Oui', 'Oui')], max_length=20)),
                ('africain', models.CharField(choices=[('Non', 'Non'), ('Oui', 'Oui')], max_length=20)),
                ('europe', models.CharField(choices=[('Non', 'Non'), ('Oui', 'Oui')], max_length=20)),
                ('buffet', models.CharField(choices=[('Non', 'Non'), ('Oui', 'Oui')], max_length=20)),
                ('camera', models.CharField(choices=[('Non', 'Non'), ('Oui', 'Oui')], max_length=20)),
                ('paiement', models.CharField(choices=[('Non', 'Non'), ('Oui', 'Oui')], max_length=20)),
                ('piscine', models.CharField(choices=[('Non', 'Non'), ('Oui', 'Oui')], max_length=20)),
                ('air', models.CharField(choices=[('Non', 'Non'), ('Oui', 'Oui')], max_length=20)),
                ('acces', models.CharField(choices=[('Non', 'Non'), ('Oui', 'Oui')], max_length=20)),
                ('amerique', models.CharField(choices=[('Non', 'Non'), ('Oui', 'Oui')], max_length=20)),
                ('wifi', models.CharField(choices=[('Non', 'Non'), ('Oui', 'Oui')], max_length=20)),
                ('repassage', models.CharField(choices=[('Non', 'Non'), ('Oui', 'Oui')], max_length=20)),
                ('conference', models.CharField(choices=[('Non', 'Non'), ('Oui', 'Oui')], max_length=20)),
                ('carte', models.CharField(choices=[('Non', 'Non'), ('Oui', 'Oui')], max_length=20)),
                ('bar', models.CharField(choices=[('Non', 'Non'), ('Oui', 'Oui')], max_length=20)),
                ('reunion', models.CharField(choices=[('Non', 'Non'), ('Oui', 'Oui')], max_length=20)),
                ('local', models.CharField(choices=[('Non', 'Non'), ('Oui', 'Oui')], max_length=20)),
                ('asiatique', models.CharField(choices=[('Non', 'Non'), ('Oui', 'Oui')], max_length=20)),
                ('handicap', models.CharField(choices=[('Non', 'Non'), ('Oui', 'Oui')], max_length=20)),
                ('extincteur', models.CharField(choices=[('Non', 'Non'), ('Oui', 'Oui')], max_length=20)),
                ('parking_prive', models.CharField(choices=[('Non', 'Non'), ('Oui', 'Oui')], max_length=20)),
                ('reservation', models.CharField(choices=[('Non', 'Non'), ('Oui', 'Oui')], max_length=20)),
            ],
        ),
    ]
