# Generated by Django 5.1.dev20240427013607 on 2024-07-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logiciel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_batiment', models.CharField(max_length=100)),
                ('img', models.FileField(null=True, upload_to='static/chargement/img')),
                ('type_lit', models.CharField(max_length=50)),
                ('ventilateur', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=20)),
                ('repas_soir', models.CharField(max_length=100)),
                ('table', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=20)),
                ('bagages', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=20)),
                ('nom_chambre', models.CharField(max_length=100)),
                ('type_chambre', models.CharField(choices=[('premium', 'premium'), ('standard', 'standard'), ('suite royale', 'suite royale')], max_length=50)),
                ('climatiseur', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=20)),
                ('repas_matin', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=20)),
                ('eau_chaude', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=20)),
                ('repassage', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=20)),
                ('nbr_personne', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=20)),
                ('prix_local', models.CharField(max_length=50)),
                ('prix_online', models.CharField(max_length=50)),
                ('num_chambre', models.CharField(max_length=50)),
                ('television', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=20)),
                ('repas_midi', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=20)),
                ('type_access', models.CharField(choices=[('cle', 'cle'), ('carte', 'carte'), ('reconnaissance faciale', 'reconnaissance faciale'), ('emprunte digital', 'emprunte digital')], max_length=100)),
                ('coffre', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=20)),
            ],
        ),
    ]
