# Generated by Django 5.1.dev20240427013607 on 2024-07-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logiciel', '0002_chambre'),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('Telephone', models.CharField(max_length=100)),
                ('provenance', models.CharField(max_length=100)),
                ('type_piece', models.CharField(choices=[('CNIB', 'CNIB'), ('PASSEPORT', 'PASSEPORT'), ('CARTE CONSULAIRE', 'CARTE CONSULAIRE')], max_length=100)),
                ('num_piece', models.CharField(max_length=100)),
                ('date_expire', models.CharField(max_length=100)),
                ('remise', models.CharField(default=0, max_length=100)),
                ('date_arriver', models.CharField(max_length=100)),
                ('date_depart', models.CharField(max_length=100)),
                ('mode_paye', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('plat', 'plat'), ('boisson', 'boisson')], max_length=100)),
                ('nom_plat', models.CharField(max_length=100)),
                ('prix_unitaire', models.CharField(max_length=100)),
            ],
        ),
    ]
