# Generated by Django 5.1.dev20240427013607 on 2024-07-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logiciel', '0003_client_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='outils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_outil', models.CharField(max_length=100)),
                ('quantite', models.CharField(max_length=100)),
                ('prix_unitaire', models.CharField(max_length=100)),
            ],
        ),
    ]
