# Generated by Django 5.1.dev20240427013607 on 2024-07-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logiciel', '0004_outils'),
    ]

    operations = [
        migrations.CreateModel(
            name='administrateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_admin', models.CharField(max_length=100)),
                ('prenom_admin', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_emp', models.CharField(max_length=100)),
                ('prenom_emp', models.CharField(max_length=100)),
                ('poste', models.CharField(choices=[('Receptionniste', 'Receptionniste'), ('Nettoyage', 'Nettoyage'), ('Cuisinier', 'Cuisinier'), ('Vigile', 'Vigile'), ('Comptable', 'Comptable'), ('Chauffeur', 'Chauffeur')], max_length=100)),
                ('datenaiss', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('Telephone', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
