# Generated by Django 5.1.dev20240427013607 on 2024-08-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logiciel', '0005_administrateur_employe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employe',
            name='poste',
            field=models.CharField(max_length=100),
        ),
    ]
