# Generated by Django 5.1.dev20240427013607 on 2024-08-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logiciel', '0007_administrateur_groups_administrateur_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employe',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
