# Generated by Django 5.1.dev20240427013607 on 2024-08-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('logiciel', '0008_employe_is_active_employe_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='employe_groups', to='auth.group'),
        ),
        migrations.AddField(
            model_name='employe',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='employe',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='employe_user_permissions', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
