# Generated by Django 5.1.dev20240427013607 on 2024-08-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logiciel', '0009_employe_groups_employe_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='employe',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
