# Generated by Django 5.1.dev20240427013607 on 2024-08-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logiciel', '0010_remove_employe_groups_remove_employe_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chambre',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='static/chargement/'),
        ),
    ]
