# Generated by Django 5.1.dev20240427013607 on 2024-08-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logiciel', '0011_alter_chambre_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chambre',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='static/chargement/'),
        ),
    ]
