# Generated by Django 5.1.dev20240427013607 on 2024-08-03 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logiciel', '0013_alter_chambre_img_alter_client_remise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='remise',
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default=10, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chambre',
            name='img',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
