# Generated by Django 5.1.dev20240427013607 on 2024-08-03 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logiciel', '0014_remove_client_remise_client_email_alter_chambre_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='num_chambre',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='logiciel.chambre'),
            preserve_default=False,
        ),
    ]
