# Generated by Django 5.1.dev20240427013607 on 2024-08-03 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logiciel', '0015_client_num_chambre'),
    ]

    operations = [
        migrations.CreateModel(
            name='reserv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('Confirmée', 'Confirmée'), ('Annulée', 'Annulée'), ('En attente', 'En attente')], default='En attente', max_length=20)),
                ('sexe', models.CharField(choices=[('Masculin', 'Masculin'), ('Féminin', 'Féminin')], max_length=100)),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('mode_paiement', models.CharField(blank=True, max_length=50, null=True)),
                ('Chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logiciel.chambre')),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logiciel.client')),
                ('Emp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logiciel.employe')),
            ],
        ),
    ]
