# Generated by Django 5.1.dev20240427013607 on 2024-08-04 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logiciel', '0016_reserv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='restaurer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.CharField(max_length=100)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_jour', models.DateTimeField(auto_now_add=True)),
                ('Chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logiciel.chambre')),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logiciel.client')),
                ('Emp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logiciel.employe')),
                ('Restau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logiciel.restaurant')),
            ],
        ),
    ]
