# Generated by Django 5.1.dev20240427013607 on 2024-08-04 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logiciel', '0018_reserv_rest_alter_restaurer_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserv',
            name='jr',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='facturier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnt_verse', models.CharField(max_length=100)),
                ('remise', models.CharField(default=0, max_length=100)),
                ('total_paye', models.CharField(max_length=100)),
                ('statut', models.CharField(choices=[('Complet', 'Complet'), ('En attente', 'En attente')], default='En attente', max_length=100)),
                ('date_reglement', models.DateTimeField(auto_now_add=True)),
                ('Emp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logiciel.employe')),
                ('Reserv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logiciel.reserv')),
            ],
        ),
    ]
