# Generated by Django 5.1.dev20240427013607 on 2024-08-04 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logiciel', '0019_reserv_jr_facturier'),
    ]

    operations = [
        migrations.CreateModel(
            name='entretien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_nettoyage', models.DateField(auto_now_add=True)),
                ('Chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logiciel.chambre')),
                ('Emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logiciel.employe')),
            ],
        ),
    ]
