# Generated by Django 5.1.dev20240427013607 on 2024-08-04 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logiciel', '0020_entretien'),
    ]

    operations = [
        migrations.CreateModel(
            name='travailler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(auto_now_add=True)),
                ('date_fin', models.DateField()),
                ('mtnt', models.CharField(max_length=100)),
                ('motif', models.CharField(max_length=200)),
                ('autre_motif', models.TextField()),
                ('Chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logiciel.chambre')),
            ],
        ),
    ]
