# Generated by Django 5.1.dev20240427013607 on 2024-08-05 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logiciel', '0021_travailler'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserv',
            name='nbr_personne',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
    ]
