# Generated by Django 5.1.dev20240427013607 on 2024-08-06 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logiciel', '0022_reserv_nbr_personne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserv',
            name='rest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logiciel.restaurer'),
        ),
        migrations.CreateModel(
            name='consommation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Rest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consommations', to='logiciel.restaurer')),
                ('reserves', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consommation_details', to='logiciel.reserv')),
            ],
        ),
    ]
