# Generated by Django 5.1.dev20240427013607 on 2024-08-07 18:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logiciel', '0023_alter_reserv_rest_consommation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consommation',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
    ]
