# Generated by Django 5.1.dev20240427013607 on 2024-08-07 20:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logiciel', '0024_alter_consommation_montant'),
    ]

    operations = [
        migrations.AddField(
            model_name='consommation',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
