# Generated by Django 5.1.dev20240427013607 on 2024-08-07 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logiciel', '0025_consommation_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consommation',
            name='reserves',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consommation_details', to='logiciel.reserv'),
        ),
    ]
