# Generated by Django 5.1.dev20240427013607 on 2024-08-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logiciel', '0026_alter_consommation_reserves'),
    ]

    operations = [
        migrations.CreateModel(
            name='salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_batiment', models.CharField(max_length=100)),
                ('img', models.ImageField(null=True, upload_to='media/')),
                ('ventilateur', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=20)),
                ('nom_salle', models.CharField(max_length=100)),
                ('type_salle', models.CharField(choices=[('Conférence', 'Conférence'), ('Reception', 'Reception'), ('Autre', 'Autre')], max_length=20)),
                ('autre', models.CharField(max_length=100)),
                ('climatiseur', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], max_length=20)),
                ('nbpers', models.CharField(max_length=100)),
                ('prix_local', models.CharField(max_length=50)),
                ('num_salle', models.CharField(max_length=50)),
                ('type_access', models.CharField(choices=[('cle', 'cle'), ('carte', 'carte'), ('reconnaissance faciale', 'reconnaissance faciale'), ('emprunte digital', 'emprunte digital')], max_length=100)),
            ],
        ),
    ]
