# Generated by Django 5.1.dev20240427013607 on 2024-08-12 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logiciel', '0027_salle'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='num_salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logiciel.salle'),
        ),
        migrations.AddField(
            model_name='reserv',
            name='Salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logiciel.salle'),
        ),
        migrations.AlterField(
            model_name='client',
            name='num_chambre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logiciel.chambre'),
        ),
        migrations.AlterField(
            model_name='reserv',
            name='Chambre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logiciel.chambre'),
        ),
    ]
