# Generated by Django 5.1.dev20240427013607 on 2024-08-12 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logiciel', '0028_client_num_salle_reserv_salle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurer',
            name='Salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logiciel.salle'),
        ),
        migrations.AlterField(
            model_name='restaurer',
            name='Chambre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logiciel.chambre'),
        ),
    ]
