# Generated by Django 5.1.dev20240427013607 on 2024-08-12 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logiciel', '0029_restaurer_salle_alter_restaurer_chambre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurer',
            name='Restau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logiciel.restaurant'),
        ),
    ]
